name: appsmanager
description: appsmanager package help to connect your app with https://appsmanager.tech/.
version: 1.2.5
repository: https://github.com/Big1050/appsmanager.git
homepage: https://appsmanager.tech/

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
